import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";
import LogoProvider from "@/components/logo-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <LogoProvider>
          <body className={inter.className}>
            {children}
            <Script src="https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js" />
          </body>
        </LogoProvider>
      </ThemeProvider>
    </html>
  );
}
