export const fonts = [
    "Roboto",
    "Open Sans",
    "Noto Sans JP",
    "Montserrat",
    "Poppins",
    "Lato",
    "Inter",
    "Roboto Condensed",
    "Material Icons",
    "Oswald",
    "Roboto Mono",
    "Noto Sans",
    "Raleway",
    "Nunito Sans",
    "Nunito",
    "Rubik",
    "Playfair Display",
    "Noto Sans KR",
    "Ubuntu",
    "Roboto Slab",
    "Merriweather",
    "Noto Sans TC",
    "Source Sans 3",
    "PT Sans",
    "Kanit",
    "Plus Jakarta Sans",
    "Lora",
    "DM Sans",
    "Work Sans",
    "Mulish",
    "Fira Sans",
    "Titillium Web",
    "Barlow",
    "Manrope",
    "Quicksand",
    "IBM Plex Sans",
    "Heebo",
    "PT Serif",
    "Mukta",
    "Libre Franklin",
    "Karla",
    "Noto Serif",
    "Nanum Gothic",
    "Material Symbols Outlined",
    "Inconsolata",
    "Material Icons Outlined",
    "Noto Sans SC",
    "Josefin Sans",
    "Noto Color Emoji",
    "Bebas Neue",
    "Hind Siliguri",
    "Arimo",
    "Libre Baskerville",
    "Abel",
    "Jost",
    "Dosis",
    "EB Garamond",
    "Anton",
    "Cabin",
    "Outfit",
    "Noto Serif JP",
    "Dancing Script",
    "PT Sans Narrow",
    "Barlow Condensed",
    "Fira Sans Condensed",
    "Archivo",
    "Bitter",
    "Teko",
    "Oxygen",
    "Assistant",
    "Noto Sans HK",
    "Chakra Petch",
    "Hind",
    "Source Code Pro",
    "Cairo",
    "DM Serif Display",
    "Crimson Text",
    "Exo 2",
    "Space Grotesk",
    "Material Icons Round",
    "M PLUS Rounded 1c",
    "Prompt",
    "Pacifico",
    "Signika Negative",
    "Figtree",
    "Fjalla One",
    "Public Sans",
    "Comfortaa",
    "Red Hat Display",
    "Zilla Slab",
    "Lobster",
    "Overpass",
    "Material Icons Sharp",
    "Lilita One",
    "Asap",
    "Archivo Black",
    "Arvo",
    "Caveat",
    "Cormorant Garamond",
    "Play",
    "Rajdhani",
  "Maven Pro",
  "IBM Plex Mono",
  "Lexend",
  "Slabo 27px",
  "Barlow Semi Condensed",
  "Shadows Into Light",
  "Varela Round",
  "Rowdies",
  "Abril Fatface",
  "Tajawal",
  "Noto Sans Arabic",
  "Material Icons Two Tone",
  "Permanent Marker",
  "Sora",
  "Nanum Gothic Coding",
  "IBM Plex Serif",
  "Almarai",
  "Hind Madurai",
  "Merriweather Sans",
  "Urbanist",
  "Source Serif 4",
  "Indie Flower",
  "M PLUS 1p",
  "Questrial",
  "Nanum Myeongjo",
  "Domine",
  "Roboto Flex",
  "IBM Plex Sans Arabic",
  "Asap Condensed",
  "Changa",
  "Alegreya",
  "Catamaran",
  "Sarabun",
  "Vollkorn",
  "Satisfy",
  "Archivo Narrow",
  "Cinzel",
  "Material Symbols Rounded",
  "Frank Ruhl Libre",
  "Marcellus",
  "Acme",
  "Mate",
  "Signika",
  "Concert One",
  "Noto Kufi Arabic",
  "Be Vietnam Pro",
  "Saira Condensed",
  "Orbitron",
  "Amatic SC",
  "Exo",
  "Chivo",
  "Noto Sans Thai",
  "Great Vibes",
  "Tinos",
  "Lexend Deca",
  "Bree Serif",
  "Yanone Kaffeesatz",
  "Alfa Slab One",
  "Bungee",
  "Montserrat Alternates",
  "Cormorant",
  "Spectral",
  "Didact Gothic",
  "Cardo",
  "Alegreya Sans",
  "Amiri",
  "Mate SC",
  "Patua One",
  "Yellowtail",
  "Noto Sans Display",
  "ABeeZee",
  "Neuton",
  "Prata",
  "Passion One",
  "Kalam",
  "Righteous",
  "Readex Pro",
  "Lobster Two",
  "Inter Tight",
  "Cantarell",
  "Ubuntu Mono",
  "Martel",
  "Sawarabi Mincho",
  "Russo One",
  "Courgette",
  "Oleo Script",
  "Alata",
  "Merienda",
  "Bodoni Moda",
  "Rubik Mono One",
  "Noto Serif TC",
  "Space Mono",
  "Noticia Text",
  "Francois One",
  "Schibsted Grotesk",
  "Libre Caslon Text",
  "League Spartan",
  "Old Standard TT",
  "Ubuntu Condensed",
  "Noto Serif KR",
  "Sacramento",
  "El Messiri",
  "Sawarabi Gothic",
  "Gothic A1",
  "Josefin Slab",
  "Kaushan Script",
  "Khand",
  "Yantramanav",
  "Luckiest Guy",
  "Libre Barcode 39",
  "Alegreya Sans SC",
  "Crete Round",
  "Crimson Pro",
  "PT Sans Caption",
  "Silkscreen",
  "Philosopher",
  "DM Serif Text",
  "Zen Kaku Gothic New",
  "Encode Sans",
  "IBM Plex Sans Condensed",
  "Gruppo",
  "Albert Sans",
  "Noto Sans Bengali",
  "Antic Slab",
  "Gloria Hallelujah",
  "Rokkitt",
  "Saira",
  "Zeyada",
  "Quattrocento",
  "DM Mono",
  "Yatra One",
  "Unica One",
  "Rubik Bubbles",
  "Encode Sans Condensed",
  "Roboto Serif",
  "Special Elite",
  "Noto Sans Mono",
  "Pathway Gothic One",
  "Noto Naskh Arabic",
  "Paytone One",
  "Quattrocento Sans",
  "Unna",
  "Literata",
  "Black Ops One",
  "Gelasio",
  "News Cycle",
  "Titan One",
  "Commissioner",
  "Architects Daughter",
  "Bangers",
  "Playfair Display SC",
  "Adamina",
  "Tenor Sans",
  "Taviraj",
  "Yeseva One",
  "Advent Pro",
  "Kumbh Sans",
  "Tangerine",
  "Sen",
  "Cookie",
  "Amaranth",
  "PT Mono",
  "Poiret One",
  "Cousine",
  "Itim",
  "Staatliches",
  "Cuprum",
  "Sanchez",
  "Fira Sans Extra Condensed",
  "Courier Prime",
  "Mitr",
  "Aleo",
  "Allura",
  "Zen Maru Gothic",
  "JetBrains Mono",
  "Kosugi Maru",
  "Viga",
  "Baskervville",
  "Patrick Hand",
  "Noto Sans Devanagari",
  "Ramabhadra",
  "Sriracha",
  "Ropa Sans",
  "Mukta Malar",
  "Parisienne",
  "Red Hat Text",
  "Pridi",
  "Castoro",
  "Baloo 2",
  "Noto Serif Bengali",
  "Eczar",
  "Comic Neue",
  "Sofia",
  "Lalezar",
  "Antonio",
  "Epilogue",
  "Libre Bodoni",
  "Faustina",
  "Hind Vadodara",
  "Quantico",
  "Bad Script",
  "Koulen",
  "Handlee",
  "Abhaya Libre",
  "Gudea",
  "Vidaloka",
  "Noto Sans Tamil",
  "Noto Serif SC",
  "Jura",
  "Shippori Mincho",
  "Homemade Apple",
  "Ultra",
  "Playball",
  "Audiowide",
  "Saira Semi Condensed",
  "Sorts Mill Goudy",
  "Krub",
  "Rock Salt",
  "Press Start 2P",
  "Arsenal",
  "Alice",
  "Mandali",
  "Carter One",
  "Bai Jamjuree",
  "Alex Brush",
  "Forum",
  "Hammersmith One",
  "Syne",
  "Noto Sans Malayalam",
  "Blinker",
  "Niramit",
  "Volkhov",
  "Petrona",
  "Six Caps",
  "Julius Sans One",
  "BIZ UDPGothic",
  "Khula",
  "Reenie Beanie",
  "Macondo",
  "Changa One",
  "Fraunces",
  "VT323",
  "Baloo Bhaijaan 2",
  "Monoton",
  "Geologica",
  "Istok Web",
  ]